name: Test Issue Event
run-name: ${{ github.actor }} has created an issue.

on:
  issues:
    types:
      - opened
      - edited
      - closed

jobs:
  test_issue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print issue information
        run: |
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Issue Number: ${{ github.event.issue.number }}"
          echo "Issue Title: ${{ github.event.issue.title }}"
          echo "Action: ${{ github.event.action }}"
