name: Test Release Event
run-name: ${{ github.actor }} has created a new release.

on:
  release:
    types:
      - published
      - unpublished

jobs:
  test_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print release information
        run: |
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Release Tag Name: ${{ github.event.release.tag_name }}"
          echo "Action: ${{ github.event.action }}"
