name: Test Push Event
run-name: ${{ github.actor }} has pushed to ${{ github.ref }}

on:
  push:
    branches:
      - main

jobs:
  test_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print repository information
        run: |
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Branch: $GITHUB_REF"
          echo "Commit SHA: $GITHUB_SHA"