name: Test Pull Request Event
run-name: ${{ github.actor }} has created a pull request.

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  test_pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print pull request information
        run: |
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Pull Request Number: ${{ github.event.pull_request.number }}"
          echo "Branch: ${{ github.event.pull_request.head.ref }}"
